baseURL = "https://creditoveloce.netlify.app/"
languageCode = "en-us"
summaryLength = "10"
theme = "icelab-hugo"
title = "creditoveloce.eu"
[markup.goldmark.renderer]
unsafe = true
# [[menu.main]]
# URL = "about"
# name = "Team"
# weight = 2
[[menu.main]]
URL = "works"
name = "News"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contattaci"
weight = 4
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Pillar"
contact_form_action = "#" #form inviato in POST nella pagina contatti
description = "I finanziamenti più adatti ai tuoi progetti, senza perdere tempo."
keywords = "Creditoveloce, finanziamento, mediazione"
og_image = "images/hero/share.jpg"
footer_content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus sint magnam quia doloremque."
home = "Home"
logo = "images/logo.png"
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.js]]
URL = "plugins/plugins.js"
[[params.social]]
icon = "fa-facebook"
link = "#"
name = "facebook"
[[params.social]]
icon = "fa-twitter"
link = "#"
name = "twitter"
[[params.social]]
icon = "fa-instagram"
link = "#"
name = "instagram"

